version: '3.8'

services:
  odoo_db:
    image: postgres:14
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: always

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_config:/etc/odoo
      - odoo_addons:/mnt/extra-addons
    restart: always

volumes:
  odoo_db_data:
  odoo_data:
  odoo_config:
  odoo_addons:
